### ISSUE TITLE
How Use This Program?

### ISSUE THREAD

**Issue by dicka55** [spark/windows-device-drivers#8]
I have downloaded and extracted your files. How do I use these to install a Particle Photon driver, for which I ran the Particle link to download and extract their files (found in a Temp folder).

I tried all of your application files with no luck.

**Comment by avtolstoy** [comment]
Since you've "extracted" files, I assume you downloaded the repository sources as a zip or something like that? There is a ready to use installer executable which can be downloaded from the releases page: https://github.com/spark/windows-device-drivers/releases

Did you use that?

Latest docs.particle.io also includes a direct link to a driver installer executable: https://docs.particle.io/guide/getting-started/connect/photon/#installing-the-particle-driver

**Comment by dicka55** [comment]
Thanks for the help, much appreciated.Your first link appears to have installed one driver, but I get a message saying two more were not found.After that install I still cannot USB-connect following the Windows directions in "Connecting Over USB".
I initially got the Photon connected easily on my smart phone using my WiFi network (no cellular data plan) and played with Tinker and the two-LED example.  But later I could no longer connect. I was getting a blinking green LED (indicating a network problem). However it is now back to the proper blinking blue. But no connection through my phone or USB.
I have tried everything and am wondering if the Photon has developed a problem.Or I'm so foggy now I'm missing something. It really shouldn't be this difficult.
 

    On Sunday, December 18, 2016 6:39 AM, Andrey Tolstoy <notifications@github.com> wrote:
 

 Since you've "extracted" files, I assume you downloaded the repository sources as a zip or something like that? There is a ready to use installer executable which can be downloaded from the releases page: https://github.com/spark/windows-device-drivers/releasesDid you use that?Latest docs.particle.io also includes a direct link to a driver installer executable: https://docs.particle.io/guide/getting-started/connect/photon/#installing-the-particle-driver—

**Comment by technobly** [comment]
Closing this old issue... if you need further help please contact [Particle Support](https://docs.particle.io/support/menu-base/) or post a question in the [Particle Community](https://community.particle.io/).
